import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

# Set up figure style
plt.style.use('seaborn-v0_8-whitegrid')

# Create symmetric distribution (normal)
fig, ax = plt.subplots(figsize=(4, 3))
x = np.linspace(-4, 4, 1000)
y = stats.norm.pdf(x, 0, 1)
ax.fill_between(x, y, alpha=0.5, color='steelblue')
ax.plot(x, y, linewidth=2, color='steelblue')
ax.set_ylim(0, max(y)*1.1)
ax.set_xlim(-4, 4)
ax.set_xticks([])
ax.set_yticks([])
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_visible(False)
ax.set_xlabel('Values', fontsize=10)
ax.set_ylabel('Frequency', fontsize=10)
plt.tight_layout()
plt.savefig('assets/images/symmetric_dist.png', dpi=150, bbox_inches='tight', facecolor='white')
plt.close()

# Create right-skewed distribution (chi-square)
fig, ax = plt.subplots(figsize=(4, 3))
x = np.linspace(0, 10, 1000)
y = stats.chi2.pdf(x, 3)
ax.fill_between(x, y, alpha=0.5, color='coral')
ax.plot(x, y, linewidth=2, color='coral')
ax.set_ylim(0, max(y)*1.1)
ax.set_xlim(0, 10)
ax.set_xticks([])
ax.set_yticks([])
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_visible(False)
ax.set_xlabel('Values', fontsize=10)
ax.set_ylabel('Frequency', fontsize=10)
plt.tight_layout()
plt.savefig('assets/images/right_skewed_dist.png', dpi=150, bbox_inches='tight', facecolor='white')
plt.close()

# Create left-skewed distribution (flipped chi-square)
fig, ax = plt.subplots(figsize=(4, 3))
x = np.linspace(0, 10, 1000)
y = stats.chi2.pdf(x, 3)
# Flip horizontally
x_flipped = 10 - x
ax.fill_between(x_flipped, y, alpha=0.5, color='mediumseagreen')
ax.plot(x_flipped, y, linewidth=2, color='mediumseagreen')
ax.set_ylim(0, max(y)*1.1)
ax.set_xlim(0, 10)
ax.set_xticks([])
ax.set_yticks([])
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_visible(False)
ax.set_xlabel('Values', fontsize=10)
ax.set_ylabel('Frequency', fontsize=10)
plt.tight_layout()
plt.savefig('assets/images/left_skewed_dist.png', dpi=150, bbox_inches='tight', facecolor='white')
plt.close()

print("Distribution images created successfully!")
